### ISSUE TITLE
Include require.js

### ISSUE THREAD

**Issue by AlessandroAnnini** [FamousArchives/global-seed#2]
Hi!
what about including require.js too? can you?
this way you can load dependencies always in the same way, like
`var Engine = require('famous/core/Engine');`
instead of the "break-code"
`var Engine = Famous.Core.Engine;`

It's not an issue, i only think this could be better.

**Comment by MylesBorins** [comment]
@sun2rise thanks for chiming in.  The point of this particular seed project is to create a path for people to work with famous without using require.js

As such this request is not really in line with the needs of this project.

As always thanks for your involvement in the project!
